title: Canadian Community Builders
description: We are a curated group made by community builders for community builders.

url: https://communitybuilders.io

twitter: communi_build

collections:
  directors:
    output: true
    permalink: /directors/:path/index:output_ext

defaults:
  - scope:
      type: directors
    values:
      layout: director

gems:
- jekyll-redirect-from
- jekyll-admin
